#!/bin/bash

#this is generated by default by the script
#so please change it when you use it


initiate_dotenv(){
    echo "$1" > .env
}

append_to_dotenv(){
    echo "$1" >> .env
}

initiate_dotenv "USR_DB_HOST='localhost'"
append_to_dotenv "USR_DB_NAME='maticas_users'"
append_to_dotenv "USR_DB_USER='dave'"
append_to_dotenv "USR_DB_PASSWORD='0000'"
append_to_dotenv "USR_DB_SSLMODE='disable'"

append_to_dotenv "MQTT_IP='localhost'"
append_to_dotenv "MQTT_PORT='1883'"
append_to_dotenv "MQTT_USERNAME='dio'"
append_to_dotenv "MQTT_PASSWORD='123'"
append_to_dotenv "MQTT_CLIENT_ID='mqtt-client-1'"



